docker:
  image: yegor256/rultor-image:1.9.1
assets:
  settings.xml: yegor256/home#assets/cactoos/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
  secring.gpg: yegor256/home#assets/secring.gpg
architect:
  - victornoel
  - yegor256
install: |
  pdd -f /dev/null
merge:
  script: |
    mvn clean install -Pqulice --errors --settings ../settings.xml
    mvn clean site -Psite --errors --settings ../settings.xml
release:
  sensitive:
    - settings.xml
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    gpg --import /home/r/pubring.gpg
    gpg --allow-secret-key-import --no-tty --batch --import /home/r/secring.gpg
    mvn versions:set "-DnewVersion=${tag}" --settings ../settings.xml
    git commit -am "${tag}"
    mvn clean deploy -Pcactoos -Pqulice -Psonatype --errors --settings ../settings.xml
