assets:
  settings.xml: yegor256/home#assets/cactoos/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
  secring.gpg: yegor256/home#assets/secring.gpg
docker:
  as_root: true
install: |
  sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
architect:
- paulodamaso
- yegor256
merge:
  script: |
    pdd --file=/dev/null
    mvn clean install -Pqulice --errors --settings ../settings.xml
    mvn clean site -Psite --errors --settings ../settings.xml
deploy:
  script: |
    mvn clean deploy -Pqulice --errors --settings ../settings.xml
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}"
    mvn clean deploy -Pcactoos -Psonar -Pqulice -Psonatype --errors --settings ../settings.xml
