assets:
  settings.xml: yegor256/home#assets/cactoos/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
  secring.gpg: yegor256/home#assets/secring.gpg
docker:
  image: g4s8/rultor:alpine3.10
  as_root: true
architect:
- paulodamaso
- yegor256
merge:
  script: |
    pdd -f /dev/null
    mvn clean install -Pqulice --errors --settings ../settings.xml
    mvn clean site -Psite --errors --settings ../settings.xml
deploy:
  script: |
    pdd -f /dev/null
    mvn clean deploy -Pqulice --errors --settings ../settings.xml
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}"
    mvn clean deploy -Pcactoos -Psonar -Pqulice -Psonatype --errors --settings ../settings.xml
